packages:
  - apps/*
  - packages/*

autoInstallPeers: false
strictPeerDependencies: true
engineStrict: false
saveExact: true
verifyStoreIntegrity: true
trustLockfile: false

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false

blockExoticSubdeps: true
ignoredOptionalDependencies:
  - '@napi-rs/canvas'
strictDepBuilds: true
allowBuilds:
  esbuild@0.28.1: false
